### ISSUE TITLE
"Record not found" on GetObjects after UpdateObject

### ISSUE THREAD

**Issue by dbrandenstein** [ArunaStorage/ArunaServer#41] opened 2022-11-25 09:33 UTC
### Describe the bug
After updating an object in a collection a `GetObjectsRequest` on the collection fails with "Record not found".

### To Reproduce
1. Create a new collection
2. Add a new object to the collection (initialize and finish it)
3. Update the object, but don't finish the updated object (a finish at this point actually fails with the same error)
4. Request all objects within the collection, this fails

### Expected behavior
After the update the request to get all objects within the collection does not fail, but return an empty list of objects (the old object is removed, the updated version not yet finished).

**Comment by St4NNi** [comment] 2022-11-25 12:48
Hi, 

Thanks for your report unfortunately we were unable to reproduce this issue:

Can you please share the version you used and a short minimal (code) example which reproduces this issue on your side ?
You can omit any real IDs mockups like `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` are enough.

Thanks in advance!

**Comment by dbrandenstein** [comment] 2022-11-25 15:44
Hi, here you go: https://github.com/dbrandenstein/aos_example/tree/update-object-issue
I first thought it might be a version incompatability since I was not sure which version of the server is currently deployed on your side, but it seems to behave in the same way no matter which client version I use.
I first encountered the issue with version 0.5.0-beta.7, but the example is now using 0.5.0 and I also tried others.

**Comment by St4NNi** [comment] 2022-11-25 18:18
Hey, 

Thanks a lot for this in-depth example. With this we could finally reproduce the issue, turns out the missing HashSum was a problem (even though staging objects should not be queried in the `GetObjects` request). The issue will be fixed when [6f6fc99](https://github.com/ArunaStorage/ArunaServer/commit/6f6fc99b4097f3b0dc1425d879a9d6ce6c622d5f) is pushed to upstream.
I will leave this open till this has happend.

**Comment by St4NNi** [comment] 2022-11-29 09:41
This should be fixed by #43
Feel free to reopen this issue if any related problems still occur.

**Closed by St4NNi** 2022-11-29 09:41 UTC
Labels: bug
